name: Mark Borghi Fine Art
favicon: null
layout_spectrum: 0.21924675768241286
typography_spectrum: 0.00848369486629963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#797a7e'
    - '#c5c6c9'
    - '#a6a7ab'
  brandStrength: 0.7496870905160904
  lightness: 0.7248892094939947
  saturation: 0.8653625138103962
  rhythmicContrast: 0.5761406004894525
purpose: []
