name: Mark Borghi Fine Art
favicon: null
layout_spectrum: 0.88592
typography_spectrum: 0.23706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191c21'
    - '#dcd3c3'
    - '#24589b'
    - '#4582b7'
  brandStrength: 0.7496870905160904
  lightness: 0.7248892094939947
  saturation: 0.8653625138103962
  rhythmicContrast: 0.5761406004894525
purpose: []
